# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FrontNinja
email: bartoszwiorek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog o tematyce front-end
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.frontninja.pl" # the base hostname & protocol for your site
github_username:  bwiorek
sass:
    style: :compressed

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-paginate
paginate: 10
